name: Deploy React dist to OVH WebCloud via SSH Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build React project
        run: npm run build

      - name: Deploy dist folder to OVH via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.OVH_SFTP_USER }}
          server: ${{ secrets.OVH_SFTP_HOST }}
          port: 22
          password: ${{ secrets.OVH_SFTP_PASSWORD }}
          local_path: "./dist/*"
          remote_path: "dev/"
          args: "-o StrictHostKeyChecking=no"
          delete_remote_files: true
